In [3]:
matriz = [[1, 2], 
          [3, 4]]

for linha in matriz:
    print(linha)


[1, 2]
[3, 4]


In [7]:
matriz = []

for i in range(3):
    linha = []
    for j in range(3):
        elemento = int(input(f"Digite o numero da posição [{i+1}, {j+1}]: "))
        linha.append(elemento)
    matriz.append(linha)

print("Matriz 3x3:")
for linha in matriz:
    print(linha)


Digite o numero da posição [1, 1]:  1
Digite o numero da posição [1, 2]:  2
Digite o numero da posição [1, 3]:  3
Digite o numero da posição [2, 1]:  4
Digite o numero da posição [2, 2]:  5
Digite o numero da posição [2, 3]:  6
Digite o numero da posição [3, 1]:  7
Digite o numero da posição [3, 2]:  8
Digite o numero da posição [3, 3]:  9


Matriz 3x3:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [10]:
def recebe_dobro():
    n = int(input(f"Digite o numero a ser dobrado: ")) * 2
    return n

recebe_dobro()

Digite o numero a ser dobrado:  50


100

In [27]:
def impar_par():
    n1 = int(input(f"Digite o numero para descobrir se é ou não par: "))

    if n1 % 2 == 0:
        print(f"O numero digitado {n1} é par")
    else:
        print(f"O numero digitado {n1} é impar")

impar_par()


Digite o numero para descobrir se é ou não par:  3


O numero digitado 3 é impar


In [33]:
def soma_impares():
    lista_s_i = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    
    soma = 0  
    
    for i in lista_s_i:
        if i % 2 != 0: 
            print(i)  
            soma += i  
    
    print(f"Soma dos números ímpares: {soma}")  

soma_impares()


1
3
5
7
9
Soma dos números ímpares: 25


In [34]:
import math  

numero = float(input("Digite um número para calcular sua raiz quadrada: "))

raiz_quadrada = math.sqrt(numero)

print(f"A raiz quadrada de {numero} é {raiz_quadrada}")


Digite um número para calcular sua raiz quadrada:  2


A raiz quadrada de 2.0 é 1.4142135623730951


In [38]:
import locale
from datetime import datetime

locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')

data_str = input("Digite uma data no formato dd/mm/aaaa: ")
data = datetime.strptime(data_str, "%d/%m/%Y")
dia_da_semana = data.strftime("%A")

print(f"A data {data_str} corresponde a uma {dia_da_semana}.")


Digite uma data no formato dd/mm/aaaa:  10/01/2007


A data 10/01/2007 corresponde a uma quarta-feira.


In [40]:
import random

numero = int(input("Digite um número: "))
valor_aleatorio = random.randint(1, numero)

print(f"Valor aleatório entre 1 e {numero}: {valor_aleatorio}")

Digite um número:  500


Valor aleatório entre 1 e 500: 234


In [42]:
import random

numeros_aleatorios = [random.randint(1, 100) for _ in range(5)]

print("Lista de números aleatórios:", numeros_aleatorios)


Lista de números aleatórios: [91, 74, 24, 49, 49]


In [43]:
import time

resultado = 4  

time.sleep(2)

print(f"O resultado do lançamento do dado é: {resultado}")


O resultado do lançamento do dado é: 4


In [46]:
with open("texto.txt", "w", encoding="utf-8") as arquivo:
    arquivo.write("Python é incrível!")


In [47]:
with open("texto.txt", "r", encoding="utf-8") as arquivo:
    conteudo = arquivo.read()

print(conteudo)


Python é incrível!


In [48]:
nome = input("Digite o nome: ")
telefone = input("Digite o telefone: ")

with open("contatos.txt", "a", encoding="utf-8") as arquivo:
    arquivo.write(f"Nome: {nome}, Telefone: {telefone}\n")

print("Contato salvo com sucesso!")


Digite o nome:  Miguel 
Digite o telefone:  11942271174


Contato salvo com sucesso!


In [49]:
numero = float(input("Digite um número: "))

try:

    resultado = 100 / numero
    print(f"O resultado da divisão de 100 por {numero} é {resultado}")
except ZeroDivisionError:
    
    print("Erro! Não é possível dividir por zero.")


Digite um número:  5


O resultado da divisão de 100 por 5.0 é 20.0


In [51]:
try:
    numero = float(input("Digite um número: "))
    print(f"O número digitado foi {numero}.")
except ValueError:
    print("Erro! Você não digitou um número válido.")


Digite um número:  dajdaskl


Erro! Você não digitou um número válido.


In [53]:
try:
    numero = int(input("Digite um número inteiro: "))
    quadrado = numero ** 2
    print(f"O quadrado de {numero} é {quadrado}.")
except ValueError:
    print("Erro! Você não digitou um número inteiro válido.")

Digite um número inteiro:  20


O quadrado de 20 é 400.


In [58]:
def ler_matriz():
    matriz = []
    for i in range(5):
        linha = list(map(int, input(f"Digite os 5 elementos da linha {i+1}: ").split()))
        if len(linha) != 5:
            print("Erro! Você deve digitar exatamente 5 números por linha.")
            return None
        matriz.append(linha)
    return matriz

def calcular_somas(matriz):
    soma_linha_3 = sum(matriz[2])
    soma_coluna_2 = sum(matriz[i][1] for i in range(5))
    soma_diagonal_principal = sum(matriz[i][i] for i in range(5))
    soma_diagonal_secundaria = sum(matriz[i][4-i] for i in range(5))
    soma_total = sum(sum(linha) for linha in matriz)

    print(f"Soma da linha 3: {soma_linha_3}")
    print(f"Soma da coluna 2: {soma_coluna_2}")
    print(f"Soma da diagonal principal: {soma_diagonal_principal}")
    print(f"Soma da diagonal secundária: {soma_diagonal_secundaria}")
    print(f"Soma de todos os elementos da matriz: {soma_total}")

matriz = ler_matriz()

if matriz:
    calcular_somas(matriz)


Digite os 5 elementos da linha 1:  1 2 3 4 5
Digite os 5 elementos da linha 2:  1 2 3 4 5
Digite os 5 elementos da linha 3:  1 2 3 4 5
Digite os 5 elementos da linha 4:  1 2 3 4 5
Digite os 5 elementos da linha 5:  1 2 3 4 5


Soma da linha 3: 15
Soma da coluna 2: 10
Soma da diagonal principal: 15
Soma da diagonal secundária: 15
Soma de todos os elementos da matriz: 75


In [61]:
def ler_matriz(linhas, colunas):
    matriz = []
    for i in range(linhas):
        linha = list(map(int, input(f"Digite os {colunas} elementos da linha {i+1}: ").split()))
        if len(linha) != colunas:
            print(f"Erro! Você deve digitar exatamente {colunas} números por linha.")
            return None
        matriz.append(linha)
    return matriz

def somar_matrizes(matriz_a, matriz_b):
    matriz_s = [[matriz_a[i][j] + matriz_b[i][j] for j in range(6)] for i in range(4)]
    return matriz_s

def subtrair_matrizes(matriz_a, matriz_b):
    matriz_d = [[matriz_a[i][j] - matriz_b[i][j] for j in range(6)] for i in range(4)]
    return matriz_d

def exibir_matriz(matriz, nome):
    print(f"\nMatriz {nome}:")
    for linha in matriz:
        print(linha)

print("Digite os elementos da matriz A:")
matriz_a = ler_matriz(4, 6)

print("Digite os elementos da matriz B:")
matriz_b = ler_matriz(4, 6)

if matriz_a and matriz_b:

    matriz_s = somar_matrizes(matriz_a, matriz_b)
    matriz_d = subtrair_matrizes(matriz_a, matriz_b)

    exibir_matriz(matriz_s, "S (Soma)")
    exibir_matriz(matriz_d, "D (Diferença)")


Digite os elementos da matriz A:


Digite os 6 elementos da linha 1:  1 2 3 4 5 6 
Digite os 6 elementos da linha 2:  7 8 9 10 11 12
Digite os 6 elementos da linha 3:  13 14 15 16 17 18
Digite os 6 elementos da linha 4:  19 20 21 22 23 24


Digite os elementos da matriz B:


Digite os 6 elementos da linha 1:  25 26 27 28 29 30
Digite os 6 elementos da linha 2:  31 32 33 34 35 36 
Digite os 6 elementos da linha 3:  37 38 39 40 41 42
Digite os 6 elementos da linha 4:  43 44 45 46 47 48



Matriz S (Soma):
[26, 28, 30, 32, 34, 36]
[38, 40, 42, 44, 46, 48]
[50, 52, 54, 56, 58, 60]
[62, 64, 66, 68, 70, 72]

Matriz D (Diferença):
[-24, -24, -24, -24, -24, -24]
[-24, -24, -24, -24, -24, -24]
[-24, -24, -24, -24, -24, -24]
[-24, -24, -24, -24, -24, -24]


In [63]:
matriz = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

padroes = [
    [(0,0), (0,1), (0,2), (0,3), (1,0), (1,3), (2,0), (2,3), (3,0), (3,1), (3,2), (3,3)],  
    [(0,0), (0,1), (0,2), (0,3), (1,1), (1,2), (2,1), (2,2), (3,0), (3,1), (3,2), (3,3)],  
    [(0,0), (1,0), (2,0), (3,0), (0,1), (1,1), (2,1), (3,1), (0,2), (1,2), (2,2), (3,2)]
]

# Calculando as somas para cada padrão
for i, padrao in enumerate(padroes, start=1):
    soma = sum(matriz[x][y] for x, y in padrao)
    print(f"Soma dos elementos marcados no padrão {i}: {soma}")

Soma dos elementos marcados no padrão 1: 102
Soma dos elementos marcados no padrão 2: 102
Soma dos elementos marcados no padrão 3: 96


In [64]:
def ler_matriz(linhas, colunas):
    matriz = []
    for i in range(linhas):
        linha = list(map(int, input(f"Digite os {colunas} elementos da linha {i+1}: ").split()))
        if len(linha) != colunas:
            print(f"Erro! Você deve digitar exatamente {colunas} números por linha.")
            return None
        matriz.append(linha)
    return matriz

def verificar_elemento(matriz, x):
    for linha in matriz:
        if x in linha:
            return True
    return False

matriz_d = ler_matriz(5, 5)

if matriz_d:
    x = int(input("Digite um número X para verificar se existe na matriz: "))
    
    if verificar_elemento(matriz_d, x):
        print(f"O número {x} existe na matriz.")
    else:
        print(f"O número {x} NÃO existe na matriz.")


Digite os 5 elementos da linha 1:  1 2 3 4 5
Digite os 5 elementos da linha 2:  1 2 3 4 5
Digite os 5 elementos da linha 3:  1 2 3 4 5
Digite os 5 elementos da linha 4:  1 2 3 4 5
Digite os 5 elementos da linha 5:  1 2 3 4 5
Digite um número X para verificar se existe na matriz:  3


O número 3 existe na matriz.


In [65]:
def ler_matriz(linhas, colunas):
    matriz = []
    for i in range(linhas):
        linha = list(map(int, input(f"Digite os {colunas} elementos da linha {i+1}: ").split()))
        if len(linha) != colunas:
            print(f"Erro! Você deve digitar exatamente {colunas} números por linha.")
            return None
        matriz.append(linha)
    return matriz

def somar_linhas(matriz):
    return [sum(linha) for linha in matriz]

def somar_colunas(matriz):
    colunas = len(matriz[0])
    soma_colunas = [sum(matriz[i][j] for i in range(len(matriz))) for j in range(colunas)]
    return soma_colunas

def exibir_vetor(vetor, nome):
    print(f"\nVetor {nome}:")
    print(vetor)

matriz_g = ler_matriz(5, 5)

if matriz_g:

    vetor_sl = somar_linhas(matriz_g)
    vetor_sc = somar_colunas(matriz_g)
    
    exibir_vetor(vetor_sl, "SL (Somas das Linhas)")
    exibir_vetor(vetor_sc, "SC (Somas das Colunas)")


Digite os 5 elementos da linha 1:  1 2 3 4 5
Digite os 5 elementos da linha 2:  1 2 3 4 5
Digite os 5 elementos da linha 3:  1 2 3 4 5
Digite os 5 elementos da linha 4:  1 2 3 4 5
Digite os 5 elementos da linha 5:  1 2 3 4 5



Vetor SL (Somas das Linhas):
[15, 15, 15, 15, 15]

Vetor SC (Somas das Colunas):
[5, 10, 15, 20, 25]


In [69]:
import numpy as np

def ler_matriz():
    matriz = []
    for i in range(12):
        linha = list(map(int, input(f"Digite os 13 elementos da linha {i+1}: ").split()))
        matriz.append(linha)
    return np.array(matriz)

def modificar_matriz(matriz):
    for i in range(matriz.shape[0]):
        maior_valor = np.max(matriz[i])
        matriz[i] = matriz[i] / maior_valor
    return matriz

def exibir_matriz(matriz):
    print("\nMatriz A modificada:")
    print(matriz)

matriz_a = ler_matriz()
matriz_a_modificada = modificar_matriz(matriz_a)
exibir_matriz(matriz_a_modificada)


Digite os 13 elementos da linha 1:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 2:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 3:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 4:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 5:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 6:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 7:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 8:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 9:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 10:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 11:  1 2 3 4 5 6 7 8 9 10 11 12 13
Digite os 13 elementos da linha 12:  1 2 3 4 5 6 7 8 9 10 11 12 13



Matriz A modificada:
[[0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [2]:
import numpy as np

G = np.random.choice([1, 2, 3], 13)

print("Vetor G (Gabarito da loteria esportiva):")
print(G)

38.

import numpy as np

G = np.random.choice([1, 2, 3], 13)

Apostas = np.random.choice([0, 1], (13, 3)) 


acertos = 0
apostas_simples = 0
apostas_duplas = 0
apostas_triplas = 0

for i in range(13):
    if Apostas[i, G[i] - 1] == 1:
        acertos += 1
    total_apostas = np.sum(Apostas[i, :])
    if total_apostas == 1:
        apostas_simples += 1
    elif total_apostas == 2:
        apostas_duplas += 1
    elif total_apostas == 3:
        apostas_triplas += 1

print("Vetor G (Gabarito da loteria esportiva):", G)
print("Matriz de apostas:")
print(Apostas)
print("Número de acertos:", acertos)
print("Apostas simples:", apostas_simples)
print("Apostas duplas:", apostas_duplas)
print("Apostas triplas:", apostas_triplas)


Vetor G (Gabarito da loteria esportiva):
[2 1 1 2 3 2 3 2 1 3 2 3 2]
Vetor G (Gabarito da loteria esportiva): [2 3 1 3 1 1 1 2 2 2 3 2 3]
Matriz de apostas:
[[0 1 0]
 [0 1 0]
 [1 1 0]
 [0 1 1]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [1 0 0]
 [0 0 0]]
Número de acertos: 5
Apostas simples: 4
Apostas duplas: 5
Apostas triplas: 1


In [3]:
def soma(a, b):
    return a + b

def subtracao(a, b):
    return a - b

def multiplicacao(a, b):
    return a * b

def divisao(a, b):
    if b != 0:
        return a / b
    else:
        return "Erro! Divisão por zero."

def exibir_menu():
    print("\nSelecione a operação que deseja realizar:")
    print("1. Soma")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")

def calculadora():
    try:
        a = float(input("Digite o primeiro valor: "))
        b = float(input("Digite o segundo valor: "))
    except ValueError:
        print("Erro! Entrada inválida. Por favor, digite números válidos.")
        return

    exibir_menu()

    operacao = input("Escolha uma operação (1/2/3/4): ")

    if operacao == '1':
        print(f"O resultado da soma é: {soma(a, b)}")
    elif operacao == '2':
        print(f"O resultado da subtração é: {subtracao(a, b)}")
    elif operacao == '3':
        print(f"O resultado da multiplicação é: {multiplicacao(a, b)}")
    elif operacao == '4':
        print(f"O resultado da divisão é: {divisao(a, b)}")
    else:
        print("Operação inválida!")

calculadora()


Digite o primeiro valor:  3
Digite o segundo valor:  2



Selecione a operação que deseja realizar:
1. Soma
2. Subtração
3. Multiplicação
4. Divisão


Escolha uma operação (1/2/3/4):  3


O resultado da multiplicação é: 6.0


In [4]:
def soma(a, b):
    return a + b

def subtracao(a, b):
    return a - b

def multiplicacao(a, b):
    resultado = 0
    for _ in range(abs(int(b))):  # Realiza a soma repetida
        resultado = soma(resultado, a)  # Soma 'a' repetidamente
    if b < 0:  # Se 'b' for negativo, inverte o sinal do resultado
        resultado = -resultado
    return resultado

def divisao(a, b):
    if b != 0:
        resultado = 0
        while a >= b:
            a = subtracao(a, b)
            resultado = soma(resultado, 1)
        return resultado
    else:
        return "Erro! Divisão por zero."

def exibir_menu():
    print("\nSelecione a operação que deseja realizar:")
    print("1. Soma")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")

def calculadora():
    try:
        a = float(input("Digite o primeiro valor: "))
        b = float(input("Digite o segundo valor: "))
    except ValueError:
        print("Erro! Entrada inválida. Por favor, digite números válidos.")
        return

    exibir_menu()

    operacao = input("Escolha uma operação (1/2/3/4): ")

    if operacao == '1':
        print(f"O resultado da soma é: {soma(a, b)}")
    elif operacao == '2':
        print(f"O resultado da subtração é: {subtracao(a, b)}")
    elif operacao == '3':
        print(f"O resultado da multiplicação é: {multiplicacao(a, b)}")
    elif operacao == '4':
        print(f"O resultado da divisão é: {divisao(a, b)}")
    else:
        print("Operação inválida!")

calculadora()


Digite o primeiro valor:  3
Digite o segundo valor:  4



Selecione a operação que deseja realizar:
1. Soma
2. Subtração
3. Multiplicação
4. Divisão


Escolha uma operação (1/2/3/4):  3


O resultado da multiplicação é: 12.0


In [5]:
def velocidade_media(distancia, tempo):
    if tempo == 0:
        return "Erro! O tempo não pode ser zero."
    return distancia / tempo

distancia = float(input("Digite a distância percorrida (em metros): "))
tempo = float(input("Digite o tempo gasto (em segundos): "))

resultado = velocidade_media(distancia, tempo)

if isinstance(resultado, str):
    print(resultado)
else:
    print(f"A velocidade média é {resultado} metros por segundo.")


Digite a distância percorrida (em metros):  30
Digite o tempo gasto (em segundos):  30


A velocidade média é 1.0 metros por segundo.


In [6]:
def organizar_numero(numero):
    numero_str = str(numero)  
    lista_digitos = list(numero_str)  

    crescente = ''.join(sorted(lista_digitos))  
    decrescente = ''.join(sorted(lista_digitos, reverse=True))  
    reverso = numero_str[::-1]  

    print(f"Recebido: {numero}")
    print(f"Crescente: {crescente}")
    print(f"Decrescente: {decrescente}")
    print(f"Reverso: {reverso}")

numero = int(input("Digite um número: "))
organizar_numero(numero)


Digite um número:  10


Recebido: 10
Crescente: 01
Decrescente: 10
Reverso: 01


In [7]:
def converter_24h_para_12h(hora_24, minuto_24):
    if hora_24 == 0:
        hora_12 = 12
        periodo = 'A'
    elif hora_24 < 12:
        hora_12 = hora_24
        periodo = 'A'
    elif hora_24 == 12:
        hora_12 = 12
        periodo = 'P'
    else:
        hora_12 = hora_24 - 12
        periodo = 'P'
    
    return hora_12, minuto_24, periodo

def exibir_hora_convertida(hora_12, minuto_24, periodo):
    print(f"{hora_12}:{minuto_24:02d} {periodo}.M.")

def main():
    while True:
        try:
            hora_24 = int(input("Digite a hora (formato 24h): "))
            minuto_24 = int(input("Digite os minutos: "))
            if not (0 <= hora_24 < 24) or not (0 <= minuto_24 < 60):
                print("Por favor, insira uma hora e minutos válidos.")
                continue
        except ValueError:
            print("Entrada inválida. Digite números inteiros.")
            continue

        hora_12, minuto_12, periodo = converter_24h_para_12h(hora_24, minuto_24)
        exibir_hora_convertida(hora_12, minuto_12, periodo)

        continuar = input("\nDeseja converter outra hora? (s/n): ").strip().lower()
        if continuar != 's':
            print("Até logo!")
            break

main()

Digite a hora (formato 24h):  12
Digite os minutos:  30


12:30 P.M.



Deseja converter outra hora? (s/n):  n


Até logo!


In [8]:
import datetime

def obter_mes_por_extenso(mes):
    meses = [
        "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
        "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
    ]
    return meses[mes-1]

def validar_data(data_str):
    try:
        data = datetime.datetime.strptime(data_str, "%d/%m/%Y")
        return data
    except ValueError:
        return None

def data_com_mes_por_extenso(data_str):
    data = validar_data(data_str)
    
    if data is None:
        return None
    
    dia = data.day
    mes = data.month
    ano = data.year
    
    mes_extenso = obter_mes_por_extenso(mes)
    
    return f"{dia} de {mes_extenso} de {ano}"

# Exemplo de uso
data_input = input("Digite a data no formato DD/MM/AAAA: ")
resultado = data_com_mes_por_extenso(data_input)

if resultado:
    print(resultado)
else:
    print("Data inválida.")
import datetime

def obter_mes_por_extenso(mes):
    meses = [
        "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
        "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
    ]
    return meses[mes-1]

def validar_data(data_str):
    try:
        data = datetime.datetime.strptime(data_str, "%d/%m/%Y")
        return data
    except ValueError:
        return None

def data_com_mes_por_extenso(data_str):
    data = validar_data(data_str)
    
    if data is None:
        return None
    
    dia = data.day
    mes = data.month
    ano = data.year
    
    mes_extenso = obter_mes_por_extenso(mes)
    
    return f"{dia} de {mes_extenso} de {ano}"

# Exemplo de uso
data_input = input("Digite a data no formato DD/MM/AAAA: ")
resultado = data_com_mes_por_extenso(data_input)

if resultado:
    print(resultado)
else:
    print("Data inválida.")


Digite a data no formato DD/MM/AAAA:  10/01/2007


10 de Janeiro de 2007


Digite a data no formato DD/MM/AAAA:  29/01/2015


29 de Janeiro de 2015
